#!/usr/bin/env python3

import sys
from itertools import count

def read_input():
    for line in sys.stdin:
        yield line.strip()

def get_bus_schedule(lines):
    sched_line = list(lines)[1]
    for i, id_str in enumerate(sched_line.split(',')):
        if id_str != 'x':
            yield i, int(id_str)

def meet_schedule(t, y, offset):
    return (t + offset) % y == 0

def find_t(t0, x, y, k):
    for dt in count(step=x):
        t = t0 + dt
        if meet_schedule(t, y, k):
            return t

def main():
    schedule = get_bus_schedule(read_input())
    x = 1
    t = 0
    for offset, y in schedule:
        t = find_t(t, x, y, offset)
        x *= y

    print(t)


if __name__ == "__main__":
    main()
